In [1]:
import csv
import time
import numpy as np
np.random.seed(1)
from copy import deepcopy

In [2]:
from scipy.interpolate import interp1d

from sklearn.cross_validation import train_test_split
from sklearn.metrics import confusion_matrix

from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Reshape
from keras.layers import LSTM

Using Theano backend.


In [3]:
def read_data(filename):
    data = {}
    with open(filename, 'rb') as csvfile:
        reader = csv.reader(csvfile, delimiter=',', quotechar='|')
        for row in reader:
            block = row[-1][1:]
            if block.isdigit():
                block = int(block)
            del row[-1]
            del row[0]
            if not block in data:
                data[block] = {}
                data[block]['gyr'] = {}
                data[block]['acc'] = {}
                data[block]['gyr']['x'] = []
                data[block]['gyr']['y'] = []
                data[block]['gyr']['z'] = []
                data[block]['acc']['x'] = []
                data[block]['acc']['y'] = []
                data[block]['acc']['z'] = []
            frow = np.array(map(float, row))
            data[block]['acc']['x'].append(np.array(frow[range(0,len(row),6)]))
            data[block]['acc']['y'].append(np.array(frow[range(1,len(row),6)]))
            data[block]['acc']['z'].append(np.array(frow[range(2,len(row),6)]))
            data[block]['gyr']['x'].append(np.array(frow[range(3,len(row),6)]))
            data[block]['gyr']['y'].append(np.array(frow[range(4,len(row),6)]))
            data[block]['gyr']['z'].append(np.array(frow[range(5,len(row),6)]))
    return data

In [4]:
def inter(obs, ndots=100):
    obs = np.array(obs)
    if ndots == -1:
        return obs
    interpolated = []
    x = np.linspace(0, 100, num=obs.shape[0], endpoint=True)
    f = interp1d(x, obs, kind='slinear')
    xnew = np.linspace(0, 100, num=ndots, endpoint=True)
    interpolated.append(f(xnew))
    return interpolated

In [5]:
def array_from_dict(data, blocks=range(1, 16), ndots=-1, gyro=True, acc=True):
    X = []
    y = []
    for block in data:
        if block in blocks:
            for ind in range(len(data[block]['acc']['x'])):
                y.append(block)
                if gyro and acc:
                    X.append(np.dstack((inter(data[block]['acc']['x'][ind], ndots), 
                                        inter(data[block]['acc']['y'][ind], ndots), 
                                        inter(data[block]['acc']['z'][ind], ndots), 
                                        inter(data[block]['gyr']['x'][ind], ndots), 
                                        inter(data[block]['gyr']['y'][ind], ndots), 
                                        inter(data[block]['gyr']['z'][ind], ndots))))
                if (not gyro) and acc:
                    X.append(np.dstack((inter(data[block]['acc']['x'][ind], ndots), 
                                        inter(data[block]['acc']['y'][ind], ndots), 
                                        inter(data[block]['acc']['z'][ind], ndots))))
                if gyro and (not acc):
                    X.append(np.dstack((inter(data[block]['gyr']['x'][ind], ndots), 
                                        inter(data[block]['gyr']['y'][ind], ndots), 
                                        inter(data[block]['gyr']['z'][ind], ndots))))
    return X, np.array(y)

In [6]:
def add_noise(data, var, n):
    data_noise = deepcopy(data)
    for block in data:
        for ind in np.random.choice(range(len(data[block]['acc']['x'])), n):
            obs = np.vstack((data[block]['acc']['x'][ind], data[block]['acc']['y'][ind], 
                             data[block]['acc']['z'][ind], data[block]['gyr']['x'][ind], 
                             data[block]['gyr']['y'][ind], data[block]['gyr']['z'][ind]))
            obs = obs + np.transpose(np.random.multivariate_normal(np.zeros(6), 
                                                                   var*np.identity(6), 
                                                                   len(data[block]['gyr']['z'][ind])))
            data_noise[block]['acc']['x'].append(obs[0])
            data_noise[block]['acc']['y'].append(obs[1])
            data_noise[block]['acc']['z'].append(obs[2])
            data_noise[block]['gyr']['x'].append(obs[3])
            data_noise[block]['gyr']['y'].append(obs[4])
            data_noise[block]['gyr']['z'].append(obs[5])
            
    return data_noise

### Start from here

In [21]:
def lstm(X, y, n_units=None, n_features=None, n_epoch=None):
    b = np.zeros((len(y), 16))
    b[np.arange(len(y)), y-1] = 1
    y = b  # One hot encoded y
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
    model = Sequential()  # Creates a model
    model.add(LSTM(n_units, input_dim=n_features)) 
    model.add(Dense(16, activation='sigmoid'))  # Kind of output layer
    model.compile(loss='categorical_crossentropy',optimizer='rmsprop',metrics=['accuracy'])
    #print(model.summary())
    for seq, label in zip(X_train, y_train):
        label = label.reshape((1, -1))
        model.fit(seq, label, nb_epoch=n_epoch, batch_size=1, verbose=0)

    y_pred = []
    y_true = []
    scores = []
    for seq, label in zip(X_test, y_test):
        label = label.reshape((1, -1))
        scores.append(model.evaluate(seq, label, verbose=0)[1])
        y_pred.append(model.predict_classes(seq, verbose=0)[0])
        y_true.append(np.where(label == 1)[1][0])
    return np.mean(scores), confusion_matrix(y_true, y_pred)

In [25]:
data1 = read_data('data1.csv')  # Your data
data2 = read_data('data2.csv')  # My data (I dont have a gyroscope)
data1 = add_noise(data1, 0.5, 100)  # Your data
data2 = add_noise(data2, 0.5, 100)  # My data (I dont have a gyroscope)

1. Can you create a confusion matrix (error matrix) so that we could see if there are certain classes which are typically confused, or the recognition is poor in general.

In [26]:
X, y = array_from_dict(data1, ndots=-1)

In [27]:
scores = []
matrices = []
for i in range(3):
    s, m = lstm(X, y, n_units=120, n_features=6, n_epoch=20)
    scores.append(s)
    matrices.append(m)
print 'score: ', np.max(scores)
print 'matrix: '
print matrices[np.where(np.array(scores) == np.max(scores))[0][0]]

score:  1.0
matrix: 
[[23  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 17  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 25  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 16  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 17  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 25  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 23  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 21  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 19  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 19  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 22  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 31  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 22  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 18]]


3. can you select two very different classes (like 1 vs 9 or 11 vs 13) and test how the RNN can learn these two classes? In this case, please use much less hidden units, I think 3-10 would be enough.

In [30]:
X, y = array_from_dict(data1, blocks=[1, 9], ndots=-1) # 1 vs. 9

In [31]:
scores = []
matrices = []
for i in range(3):
    s, m = lstm(X, y, n_units=10, n_features=6, n_epoch=20) # 10 units
    scores.append(s)
    matrices.append(m)
print 'score: ', np.max(scores)
print 'matrix: '
print matrices[np.where(np.array(scores) == np.max(scores))[0][0]]

score:  1.0
matrix: 
[[26  0]
 [ 0 19]]


In [32]:
scores = []
matrices = []
for i in range(3):
    s, m = lstm(X, y, n_units=40, n_features=6, n_epoch=20) # 40 units
    scores.append(s)
    matrices.append(m)
print 'score: ', np.max(scores)
print 'matrix: '
print matrices[np.where(np.array(scores) == np.max(scores))[0][0]]

WARNING (theano.gof.compilelock): Overriding existing lock by dead process '5744' (I am process '5602')


score:  1.0
matrix: 
[[26  0]
 [ 0 19]]


In [33]:
X, y = array_from_dict(data1, blocks=[11, 13], ndots=-1) # 11 vs. 13

In [34]:
scores = []
matrices = []
for i in range(3):
    s, m = lstm(X, y, n_units=10, n_features=6, n_epoch=20) # 10 units
    scores.append(s)
    matrices.append(m)
print 'score: ', np.max(scores)
print 'matrix: '
print matrices[np.where(np.array(scores) == np.max(scores))[0][0]]

score:  0.886363636364
matrix: 
[[24  2]
 [ 3 15]]


In [35]:
scores = []
matrices = []
for i in range(3):
    s, m = lstm(X, y, n_units=40, n_features=6, n_epoch=20) # 40 units
    scores.append(s)
    matrices.append(m)
print 'score: ', np.max(scores)
print 'matrix: '
print matrices[np.where(np.array(scores) == np.max(scores))[0][0]]

score:  1.0
matrix: 
[[26  0]
 [ 0 18]]


4. can you  reduce the sampling rate? Maybe there is a very little difference in data points at subsequent time positions like t and t+1. Would you invesitgate the performance when only every 10th or 20th data point is kept in the time seris?

In [36]:
X, y = array_from_dict(data1, ndots=10) # each sequence is interpoleted to 10 points

In [37]:
scores = []
matrices = []
for i in range(3):
    s, m = lstm(X, y, n_units=120, n_features=6, n_epoch=20)
    scores.append(s)
    matrices.append(m)
print 'score: ', np.max(scores)
print 'matrix: '
print matrices[np.where(np.array(scores) == np.max(scores))[0][0]]

score:  0.996904024768
matrix: 
[[23  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 17  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 25  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 16  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 17  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 25  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 23  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 21  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 19  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 19  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 21  0  1  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 31  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 22  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 18]]


5. Can you try RNN on your data (i.e. which does not have gyroscope data). Likewise, can you try using only acc or only gyro data from my data?
 

In [38]:
X, y = array_from_dict(data1, ndots=-1, gyro=False) # your data; acceleration only

In [39]:
scores = []
matrices = []
for i in range(3):
    s, m = lstm(X, y, n_units=120, n_features=3, n_epoch=20)
    scores.append(s)
    matrices.append(m)
print 'score: ', np.max(scores)
print 'matrix: '
print matrices[np.where(np.array(scores) == np.max(scores))[0][0]]

score:  0.996904024768
matrix: 
[[23  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 17  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 25  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 16  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 17  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 25  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 23  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 21  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 19  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 19  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 22  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 31  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  0 21  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 18]]


In [40]:
X, y = array_from_dict(data1, ndots=-1, acc=False) # your data; gyroscope only

In [41]:
scores = []
matrices = []
for i in range(3):
    s, m = lstm(X, y, n_units=120, n_features=3, n_epoch=20)
    scores.append(s)
    matrices.append(m)
print 'score: ', np.max(scores)
print 'matrix: '
print matrices[np.where(np.array(scores) == np.max(scores))[0][0]]

score:  0.0712074303406
matrix: 
[[23  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [17  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [25  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [16  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [17  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [25  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [23  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [21  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [19  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [19  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [22  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [31  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [25  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [22  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [18  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]


In [42]:
X, y = array_from_dict(data2, ndots=-1, gyro=False) # my data; acceleration only

In [43]:
scores = []
matrices = []
for i in range(3):
    s, m = lstm(X, y, n_units=120, n_features=3, n_epoch=20)
    scores.append(s)
    matrices.append(m)
print 'score: ', np.max(scores)
print 'matrix: '
print matrices[np.where(np.array(scores) == np.max(scores))[0][0]]

score:  0.885196374622
matrix: 
[[23  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 18  0  0  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  0 26  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 14  0  0  0  0  0  0  4  1  0  0  0]
 [ 0  0  0  0 15  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0 22  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 24  0  1  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0 18  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 18  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0 19  0  0  0  0  0]
 [ 0  0  1  0  0  0  2  0  0  0 18  0  3  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0 28  0  0  0]
 [ 0  0  0  0  1  0  0  0  8  0  0  0 19  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  0 16  0]
 [ 0  0  1  0  0  0  0  0  0  0  0  4  1  0 15]]
